<?php
declare(strict_types=1);

if(!isset($asyuraCurrentSite)||!is_array($asyuraCurrentSite)){echo '<div class="empty-state">サイトが選択されていません。</div>';return;}
$siteId=(int)$asyuraCurrentSite['id'];$q=$db->prepare('SELECT * FROM sites WHERE id=?');$q->execute([$siteId]);$site=$q->fetch()?:$asyuraCurrentSite;
$inquiryUrl=app_url('public/inquiry.php?site='.rawurlencode((string)$site['public_id']));$requestUrl=app_url('public/contact.php?site='.rawurlencode((string)$site['public_id']));$inquiryTag='<iframe src="'.$inquiryUrl.'" loading="lazy" style="width:100%;height:850px;border:0"></iframe>';$requestTag='<iframe src="'.$requestUrl.'" loading="lazy" style="width:100%;height:1000px;border:0"></iframe>';
echo '<div class="notice info"><strong>一般お問い合わせと相互リンク申請を分離しています。</strong> このページでは、それぞれの公開URLを確認できます。</div>';
echo '<div class="panel contact-panel"><h2>一般お問い合わせフォーム</h2><div class="panel-body"><p>対象サイト：<strong>'.e($site['name']).'</strong></p><label class="standalone-field">公開URL<input value="'.e($inquiryUrl).'" readonly></label><div class="actions contact-actions"><a class="button primary" href="'.e($inquiryUrl).'" target="_blank" rel="noopener">フォームを確認</a><a class="button secondary" href="'.e(app_url('admin/?page=inquiries&site='.$siteId)).'">受信一覧を開く</a></div><section class="embed-code-section"><h3>サイトへの設置タグ</h3><p class="description">このコードをお問い合わせを表示したい場所へ貼り付けます。</p><pre id="inquiry-tag" class="codebox">'.e($inquiryTag).'</pre><button type="button" class="button" data-copy="#inquiry-tag">設置タグをコピー</button></section><p class="description contact-note">通知先：'.e($site['admin_email']?:'管理メールアドレス未設定').'。未設定でも管理画面には保存されます。</p></div></div>';
echo '<div class="panel contact-panel"><h2>相互リンク申請フォーム</h2><div class="panel-body"><p>一般お問い合わせとは別の、相互リンク申請専用フォームです。</p><label class="standalone-field">公開URL<input value="'.e($requestUrl).'" readonly></label><div class="actions contact-actions"><a class="button primary" href="'.e($requestUrl).'" target="_blank" rel="noopener">申請フォームを確認</a><a class="button secondary" href="'.e(app_url('admin/?page=requests&site='.$siteId)).'">申請一覧を開く</a></div><section class="embed-code-section"><h3>サイトへの設置タグ</h3><p class="description">このコードを相互リンク申請フォームを表示したい場所へ貼り付けます。</p><pre id="reciprocal-request-tag" class="codebox">'.e($requestTag).'</pre><button type="button" class="button" data-copy="#reciprocal-request-tag">設置タグをコピー</button></section>'.(empty($site['links_enabled'])?'<p class="notice warning">相互リンク機能が停止中のため、このフォームは現在公開されません。</p>':'').'</div></div>';
echo '<div class="panel contact-panel"><h2>相互リンク申請フォーム上部の案内</h2><div class="panel-body"><form method="post">'.csrf_field().'<input type="hidden" name="action" value="save_contact_settings"><input type="hidden" name="context_site_id" value="'.$siteId.'"><div class="checks contact-options"><label><input type="checkbox" name="contact_ads_notice" '.(!empty($site['contact_ads_notice'])?'checked':'').'>広告は募集していない旨を表示</label><label><input type="checkbox" name="contact_links_notice" '.(!empty($site['contact_links_notice'])?'checked':'').'>広告・相互リンクは募集していない旨を表示</label><label><input type="checkbox" name="contact_custom_enabled" '.(!empty($site['contact_custom_enabled'])?'checked':'').'>自由入力文を表示</label></div><label class="standalone-field">自由入力文<textarea name="contact_custom_text" rows="5">'.e($site['contact_custom_text']??'').'</textarea></label><div class="actions"><button class="button primary">案内設定を保存</button></div></form></div></div>';
