<?php
declare(strict_types=1);

if(!isset($asyuraCurrentSite)||!is_array($asyuraCurrentSite)){echo '<div class="empty-state">サイトが選択されていません。</div>';return;}
$siteId=(int)$asyuraCurrentSite['id'];$statuses=['unread'=>'未読','reviewing'=>'確認中','resolved'=>'対応済み'];$id=(int)($_GET['id']??0);

if($id>0){
    $q=$db->prepare('SELECT * FROM contact_messages WHERE id=? AND site_id=? LIMIT 1');$q->execute([$id,$siteId]);$message=$q->fetch();
    if(!$message){echo '<div class="notice error">選択中のサイトに、このお問い合わせはありません。</div>';return;}
    echo '<div class="page-actions"><a class="button" href="'.e(app_url('admin/?page=inquiries&site='.$siteId)).'">受信一覧へ戻る</a></div><div class="panel"><h2>'.e($message['subject']).'</h2><div class="panel-body"><div class="inquiry-meta"><div><span>状態</span><strong class="inquiry-status '.e($message['status']).'">'.e($statuses[$message['status']]??$message['status']).'</strong></div><div><span>受付番号</span><strong>'.e($message['receipt_no']).'</strong></div><div><span>受信日時</span><strong>'.e($message['created_at']).'</strong></div></div><dl class="inquiry-detail"><dt>お名前</dt><dd>'.e($message['sender_name']).'</dd><dt>メールアドレス</dt><dd><a href="mailto:'.e($message['sender_email']).'">'.e($message['sender_email']).'</a></dd><dt>お問い合わせ内容</dt><dd>'.nl2br(e($message['message'])).'</dd></dl></div></div>';
    echo '<div class="panel"><h2>対応状況</h2><div class="panel-body"><form method="post">'.csrf_field().'<input type="hidden" name="action" value="update_inquiry_status"><input type="hidden" name="context_site_id" value="'.$siteId.'"><input type="hidden" name="id" value="'.$id.'"><label>状態<select name="status">';foreach($statuses as$key=>$label)echo '<option value="'.e($key).'"'.($message['status']===$key?' selected':'').'>'.e($label).'</option>';echo '</select></label><button class="button primary">状態を保存</button></form></div></div>';return;
}

$filter=(string)($_GET['status']??'all');if($filter!=='all'&&!array_key_exists($filter,$statuses))$filter='all';
$q=$db->prepare("SELECT COUNT(*) total,COALESCE(SUM(status='unread'),0) unread,COALESCE(SUM(status='reviewing'),0) reviewing,COALESCE(SUM(status='resolved'),0) resolved FROM contact_messages WHERE site_id=?");$q->execute([$siteId]);$counts=$q->fetch()?:[];
echo '<div class="analytics-cards inquiry-cards"><div class="analytics-card red"><span>未読</span><strong>'.number_format((int)($counts['unread']??0)).'</strong></div><div class="analytics-card blue"><span>確認中</span><strong>'.number_format((int)($counts['reviewing']??0)).'</strong></div><div class="analytics-card green"><span>対応済み</span><strong>'.number_format((int)($counts['resolved']??0)).'</strong></div></div>';
$url=static fn(string $status):string=>app_url('admin/?page=inquiries&site='.$siteId.'&status='.$status);echo '<div class="analytics-toolbar"><span>表示</span><a class="range-button'.($filter==='all'?' active':'').'" href="'.e($url('all')).'">すべて</a>';foreach($statuses as$key=>$label)echo '<a class="range-button'.($filter===$key?' active':'').'" href="'.e($url($key)).'">'.e($label).'</a>';echo '<a class="button" href="'.e(app_url('admin/?page=contact&site='.$siteId)).'">フォーム設定</a></div>';
$sql='SELECT id,receipt_no,status,sender_name,sender_email,subject,created_at FROM contact_messages WHERE site_id=?';$params=[$siteId];if($filter!=='all'){$sql.=' AND status=?';$params[]=$filter;}$sql.=' ORDER BY created_at DESC,id DESC LIMIT 500';$q=$db->prepare($sql);$q->execute($params);$rows=$q->fetchAll();
echo '<div class="panel"><h2>'.e($asyuraCurrentSite['name']).'のお問い合わせ</h2><div class="table-wrap"><table class="wp-list"><thead><tr><th>状態</th><th>件名・お名前</th><th>メールアドレス</th><th>受信日時</th></tr></thead><tbody>';foreach($rows as$row)echo '<tr><td><span class="inquiry-status '.e($row['status']).'">'.e($statuses[$row['status']]??$row['status']).'</span></td><td><a href="'.e(app_url('admin/?page=inquiries&site='.$siteId.'&id='.(int)$row['id'])).'"><strong>'.e($row['subject']).'</strong></a><br><small>'.e($row['sender_name']).' / '.e($row['receipt_no']).'</small></td><td>'.e($row['sender_email']).'</td><td>'.e($row['created_at']).'</td></tr>';if($rows===[])echo '<tr><td colspan="4" class="empty">該当するお問い合わせはありません。</td></tr>';echo '</tbody></table></div></div><p class="description">最新500件までを表示します。お問い合わせは選択中のサイトだけに限定されています。</p>';
