<?php
declare(strict_types=1);

use Asyura\Security;

function asyura_sites(PDO $db): array
{
    return $db->query('SELECT * FROM sites ORDER BY id DESC')->fetchAll();
}

function asyura_current_site(): ?array
{
    global $asyuraCurrentSite;
    return is_array($asyuraCurrentSite) ? $asyuraCurrentSite : null;
}

function asyura_current_site_id(): int
{
    return (int) (asyura_current_site()['id'] ?? 0);
}

function asyura_context_field(): string
{
    return '<input type="hidden" name="context_site_id" value="' . asyura_current_site_id() . '">';
}

function asyura_require_current_site(): int
{
    $siteId = asyura_current_site_id();
    if ($siteId === 0) {
        echo '<div class="empty-state"><strong>管理サイトが登録されていません。</strong><p>「サイト管理」から最初のサイトを登録してください。</p><a class="button primary" href="' . e(app_url('admin/?page=sites&new=1')) . '">サイトを登録</a></div>';
    }
    return $siteId;
}

function asyura_page_dashboard(PDO $db, array $config): void
{
    $siteId = asyura_require_current_site();
    if (!$siteId) return;
    $todayStmt=$db->prepare("SELECT COALESCE(SUM(pv),0) pv,COALESCE(SUM(uu),0) uu,COALESCE(SUM(outbound),0) outbound FROM daily_stats WHERE site_id=? AND stat_date=CURDATE()");$todayStmt->execute([$siteId]);$today=$todayStmt->fetch();
    $requestStmt=$db->prepare("SELECT COUNT(*) FROM link_requests WHERE site_id=? AND status='new'");$requestStmt->execute([$siteId]);$requests=(int)$requestStmt->fetchColumn();
    $errorStmt=$db->prepare("SELECT COUNT(*) FROM rss_feeds WHERE site_id=? AND active=1 AND last_error IS NOT NULL");$errorStmt->execute([$siteId]);$feedErrors=(int)$errorStmt->fetchColumn();
    echo '<div class="welcome-panel"><div><span class="eyebrow">SITE OVERVIEW</span><h2>'.e(asyura_current_site()['name']).'の今日の状況</h2><p>解析・相互管理の重要な数字をまとめて確認できます。</p></div><a class="button" href="'.e(app_url('admin/?page=sites&edit='.$siteId)).'">サイト設定を開く</a></div>';
    echo '<div class="cards"><div class="card"><div class="card-icon blue">PV</div><div><div class="number">' . number_format((int) $today['pv']) . '</div><div class="label">今日のPV</div></div></div><div class="card green"><div class="card-icon green">UU</div><div><div class="number">' . number_format((int) $today['uu']) . '</div><div class="label">今日のUU</div></div></div><div class="card orange"><div class="card-icon orange">OUT</div><div><div class="number">' . number_format((int) $today['outbound']) . '</div><div class="label">外部クリック</div></div></div><div class="card purple"><div class="card-icon purple">依頼</div><div><div class="number">' . $requests . '</div><div class="label">未確認の相互リンク依頼</div></div></div></div>';
    echo '<div class="panel"><h2>直近14日間のアクセス</h2><div class="panel-body">';
    $rowStmt=$db->prepare("SELECT stat_date,pv FROM daily_stats WHERE site_id=? AND stat_date>=CURDATE()-INTERVAL 13 DAY ORDER BY stat_date");$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();
    $max = max(1, ...array_map(static fn($r)=>(int)$r['pv'], $rows ?: [['pv'=>1]]));
    if (!$rows) echo '<div class="empty">まだアクセスデータがありません。</div>'; else { echo '<div class="chart-bars">'; foreach ($rows as $r) echo '<span title="'.e($r['stat_date'].'：'.$r['pv'].' PV').'" style="height:'.max(3,round(((int)$r['pv']/$max)*100)).'%"></span>'; echo '</div>'; }
    echo '</div></div><div class="cards compact"><div class="card ' . ($feedErrors ? 'orange' : 'green') . '"><div class="number">' . $feedErrors . '</div><div class="label">このサイトのRSS取得エラー</div></div></div>';
    echo '<div class="panel"><h2>設定状況</h2><div class="panel-body"><p>cron URL：<code>' . e(app_url('cron/run.php?key=' . $config['cron_key'])) . '</code></p><p class="description">30分ごとにcronを実行してください。CLIからは <code>php ' . e(ASYURA_ROOT . '/cron/run.php') . '</code> でも実行できます。</p></div></div>';
}

function asyura_page_sites(PDO $db, array $config): void
{
    $edit = (int) ($_GET['edit'] ?? 0);
    if (isset($_GET['new']) || $edit) {
        $site = ['id'=>0,'name'=>'','url'=>'','category'=>'','description'=>'','admin_email'=>'','active'=>1,'ranking_enabled'=>1,'links_enabled'=>1,'rss_enabled'=>1,'rotation_enabled'=>0,'is_priority'=>0,'priority_multiplier'=>'1.50','is_special'=>0,'special_points'=>'100','is_rescue'=>0,'rescue_min_points'=>'1','is_excluded'=>0,'contact_ads_notice'=>0,'contact_links_notice'=>0,'contact_custom_enabled'=>0,'contact_custom_text'=>''];
        if ($edit) { $s=$db->prepare('SELECT * FROM sites WHERE id=?'); $s->execute([$edit]); $site=$s->fetch() ?: $site; }
        echo '<form method="post"><input type="hidden" name="action" value="save_site"><input type="hidden" name="id" value="'.(int)$site['id'].'">'.csrf_field().'<div class="panel"><h2>基本情報</h2><div class="panel-body"><div class="form-grid"><label>サイト名<input name="name" value="'.e($site['name']).'" required></label><label>サイトURL<input type="url" name="url" value="'.e($site['url']).'" placeholder="https://example.com" required></label><label>カテゴリー<input name="category" value="'.e($site['category']).'"></label><label>管理者メール<input type="email" name="admin_email" value="'.e($site['admin_email']).'"></label><label class="span-2">説明<textarea name="description">'.e($site['description']).'</textarea></label></div><div class="checks">';
        foreach (['active'=>'計測有効','ranking_enabled'=>'ランキング','links_enabled'=>'相互リンク','rss_enabled'=>'相互RSS','rotation_enabled'=>'過去記事再配信'] as $k=>$v) echo '<label><input type="checkbox" name="'.$k.'" '.(!empty($site[$k])?'checked':'').'>'.$v.'</label>';
        echo '</div></div></div><div class="panel"><h2>配分・除外</h2><div class="panel-body"><div class="checks"><label><input type="checkbox" name="is_priority" '.(!empty($site['is_priority'])?'checked':'').'>優遇サイト</label><label><input type="checkbox" name="is_special" '.(!empty($site['is_special'])?'checked':'').'>特別サイト</label><label><input type="checkbox" name="is_rescue" '.(!empty($site['is_rescue'])?'checked':'').'>弱小サイト救済</label><label><input type="checkbox" name="is_excluded" '.(!empty($site['is_excluded'])?'checked':'').'>除外サイト</label></div><div class="form-grid"><label>優遇倍率<input type="number" step="0.01" min="0" name="priority_multiplier" value="'.e($site['priority_multiplier']).'"></label><label>特別配分ポイント<input type="number" step="0.01" min="0" name="special_points" value="'.e($site['special_points']).'"></label><label>弱小サイト最低ポイント<input type="number" step="0.01" min="0" name="rescue_min_points" value="'.e($site['rescue_min_points']).'"></label></div></div></div>';
        echo '<div class="panel"><h2>お問い合わせ上部の案内文</h2><div class="panel-body"><div class="checks"><label><input type="checkbox" name="contact_ads_notice" '.(!empty($site['contact_ads_notice'])?'checked':'').'>「現在、広告は募集しておりません。」を表示</label><label><input type="checkbox" name="contact_links_notice" '.(!empty($site['contact_links_notice'])?'checked':'').'>「現在、広告や相互リンクは募集しておりません。」を表示</label><label><input type="checkbox" name="contact_custom_enabled" '.(!empty($site['contact_custom_enabled'])?'checked':'').'>自由入力文を表示</label></div><label>自由入力文<textarea name="contact_custom_text">'.e($site['contact_custom_text']).'</textarea></label></div></div><div class="actions"><button class="button primary">保存</button><a class="button" href="'.e(app_url('admin/?page=sites')).'">戻る</a></div></form>';
        if ($edit) {
            $tag='<script src="'.app_url('assets/tracker.js').'" data-site-id="'.$site['public_id'].'" data-site-key="'.$site['site_key'].'" async></script>';
            $contactUrl=app_url('public/contact.php?site='.$site['public_id']);
            echo '<div class="panel"><h2>計測タグ</h2><div class="panel-body"><p>このサイトの全ページへ同じタグを設置します。</p><pre id="tracking-tag" class="codebox">'.e($tag).'</pre><button type="button" class="button" data-copy="#tracking-tag">コピー</button></div></div><div class="panel"><h2>相互リンク依頼フォーム</h2><div class="panel-body"><p><a href="'.e($contactUrl).'" target="_blank" rel="noopener">'.e($contactUrl).'</a></p><pre id="contact-tag" class="codebox">'.e('<iframe src="'.$contactUrl.'" loading="lazy" style="width:100%;height:900px;border:0"></iframe>').'</pre><button type="button" class="button" data-copy="#contact-tag">コピー</button></div></div>';
            echo '<div class="danger-zone"><h2>サイトを完全削除</h2><p>関連する解析・RSS・ランキング・相互リンクデータもすべて削除され、元に戻せません。</p><form method="post" data-confirm="本当にサイトと関連データを完全削除しますか？"><input type="hidden" name="action" value="delete_site"><input type="hidden" name="id" value="'.(int)$site['id'].'">'.csrf_field().'<label><input type="radio" name="confirm_delete" value="no" checked>いいえ</label><label><input type="radio" name="confirm_delete" value="yes">はい、削除します</label><button class="button danger">削除を実行</button></form></div>';
        }
        return;
    }
    echo '<div class="section-intro"><div><h2>管理サイト一覧</h2><p>計測タグを設置して阿修羅で管理するサイトです。提携サイトや相互リンク先とは別です。</p></div><a class="button primary" href="'.e(app_url('admin/?page=sites&new=1')).'">サイトを追加</a></div><div class="table-wrap"><table class="wp-list"><thead><tr><th>管理サイト</th><th>状態</th><th>利用機能</th><th>操作</th></tr></thead><tbody>';
    foreach (asyura_sites($db) as $s) { echo '<tr><td><strong>'.e($s['name']).'</strong><br><a href="'.e($s['url']).'" target="_blank" rel="noopener">'.e($s['url']).'</a></td><td><span class="badge '.($s['active']?'active':'').'">'.($s['active']?'計測中':'停止').'</span> '.($s['is_priority']?'<span class="badge priority">優遇</span> ':'').($s['is_special']?'<span class="badge special">特別</span> ':'').($s['is_rescue']?'<span class="badge rescue">救済</span> ':'').($s['is_excluded']?'<span class="badge">除外</span>':'').'</td><td>解析 '.($s['ranking_enabled']?'／ランキング':'').' '.($s['rss_enabled']?'／RSS':'').'</td><td><a class="button primary" href="'.e(app_url('admin/?page=dashboard&site='.$s['id'])).'">このサイトを管理</a> <a class="button" href="'.e(app_url('admin/?page=sites&site='.$s['id'].'&edit='.$s['id'])).'">設定</a></td></tr>'; }
    if (!asyura_sites($db)) echo '<tr><td colspan="4" class="empty">サイトを登録してください。</td></tr>';
    echo '</tbody></table></div>';
}

function asyura_page_analytics(PDO $db, array $config): void
{
    $siteId=asyura_require_current_site();
    if(!$siteId)return;
    echo '<div class="section-intro"><div><h2>アクセス解析レポート</h2><p>現在選択しているサイトのデータだけを表示しています。</p></div><span class="scope-badge">'.e(asyura_current_site()['name']).' 専用</span></div>';
    $s=$db->prepare("SELECT COALESCE(SUM(pv),0) pv,COALESCE(SUM(uu),0) uu,COALESCE(SUM(outbound),0) outbound,COALESCE(SUM(internal_clicks),0) internal_clicks,COALESCE(SUM(widget_clicks),0) clicks FROM daily_stats WHERE site_id=? AND stat_date>=CURDATE()-INTERVAL 29 DAY");$s->execute([$siteId]);$sum=$s->fetch();
    $sessionStmt=$db->prepare("SELECT COUNT(DISTINCT session_hash) FROM raw_events WHERE site_id=? AND event_type='pageview' AND is_bot=0 AND occurred_at>=NOW()-INTERVAL 30 DAY");$sessionStmt->execute([$siteId]);$sessions=(int)$sessionStmt->fetchColumn();echo '<div class="cards"><div class="card"><div class="number">'.number_format((int)$sum['pv']).'</div><div class="label">30日PV</div></div><div class="card green"><div class="number">'.number_format((int)$sum['uu']).'</div><div class="label">30日UU</div></div><div class="card"><div class="number">'.number_format($sessions).'</div><div class="label">セッション</div></div><div class="card orange"><div class="number">'.number_format((int)$sum['outbound']).'</div><div class="label">外部クリック</div></div><div class="card purple"><div class="number">'.number_format((int)$sum['internal_clicks']).'</div><div class="label">ページ内リンク</div></div></div>';
    $q=$db->prepare('SELECT stat_date,pv,uu,outbound,internal_clicks,widget_clicks FROM daily_stats WHERE site_id=? ORDER BY stat_date DESC LIMIT 30');$q->execute([$siteId]);echo '<div class="panel"><h2>日別アクセス</h2><div class="table-wrap"><table class="wp-list"><tr><th>日付</th><th>PV</th><th>UU</th><th>ページ内</th><th>外部</th><th>パーツ</th></tr>';foreach($q as $r)echo '<tr><td>'.e($r['stat_date']).'</td><td>'.number_format((int)$r['pv']).'</td><td>'.number_format((int)$r['uu']).'</td><td>'.number_format((int)$r['internal_clicks']).'</td><td>'.number_format((int)$r['outbound']).'</td><td>'.number_format((int)$r['widget_clicks']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare('SELECT referrer_host,SUM(inbound) inbound,SUM(unique_inbound) unique_inbound FROM referrer_stats WHERE site_id=? AND stat_date>=CURDATE()-INTERVAL 29 DAY GROUP BY referrer_host ORDER BY inbound DESC LIMIT 100');$q->execute([$siteId]);echo '<div class="panel"><h2>流入元ランキング</h2><div class="table-wrap"><table class="wp-list"><tr><th>流入元</th><th>IN</th><th>UU</th></tr>';foreach($q as $r)echo '<tr><td>'.e($r['referrer_host']).'</td><td>'.number_format((int)$r['inbound']).'</td><td>'.number_format((int)$r['unique_inbound']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare("SELECT page_title,normalized_page_url,COUNT(*) views,COUNT(DISTINCT visitor_hash) visitors FROM raw_events WHERE site_id=? AND event_type='pageview' AND is_bot=0 AND occurred_at>=NOW()-INTERVAL 30 DAY GROUP BY normalized_page_url,page_title ORDER BY views DESC LIMIT 50");$q->execute([$siteId]);echo '<div class="panel"><h2>人気ページ</h2><div class="table-wrap"><table class="wp-list"><tr><th>ページ</th><th>PV</th><th>訪問者</th></tr>';foreach($q as $r)echo '<tr><td><strong>'.e($r['page_title']?:'(タイトルなし)').'</strong><br><small>'.e($r['normalized_page_url']).'</small></td><td>'.number_format((int)$r['views']).'</td><td>'.number_format((int)$r['visitors']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare("SELECT e.page_title,e.normalized_page_url,COUNT(*) landings FROM raw_events e JOIN (SELECT session_hash,MIN(id) first_id FROM raw_events WHERE site_id=? AND event_type='pageview' AND is_bot=0 AND occurred_at>=NOW()-INTERVAL 30 DAY GROUP BY session_hash) firsts ON firsts.first_id=e.id GROUP BY e.normalized_page_url,e.page_title ORDER BY landings DESC LIMIT 50");$q->execute([$siteId]);echo '<div class="panel"><h2>ランディングページ</h2><div class="table-wrap"><table class="wp-list"><tr><th>最初に閲覧したページ</th><th>セッション</th></tr>';foreach($q as $r)echo '<tr><td><strong>'.e($r['page_title']?:'(タイトルなし)').'</strong><br><small>'.e($r['normalized_page_url']).'</small></td><td>'.number_format((int)$r['landings']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare('SELECT target_url,SUM(internal_clicks) internal_clicks,SUM(outbound_clicks) outbound_clicks,SUM(widget_clicks) widget_clicks FROM daily_link_stats WHERE site_id=? AND stat_date>=CURDATE()-INTERVAL 29 DAY GROUP BY target_hash,target_url ORDER BY (SUM(internal_clicks)+SUM(outbound_clicks)+SUM(widget_clicks)) DESC LIMIT 50');$q->execute([$siteId]);echo '<div class="panel"><h2>クリック先</h2><div class="table-wrap"><table class="wp-list"><tr><th>リンク先</th><th>ページ内</th><th>外部</th><th>パーツ</th></tr>';foreach($q as $r)echo '<tr><td>'.e($r['target_url']).'</td><td>'.number_format((int)$r['internal_clicks']).'</td><td>'.number_format((int)$r['outbound_clicks']).'</td><td>'.number_format((int)$r['widget_clicks']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare("SELECT device,browser,os,COUNT(*) views FROM raw_events WHERE site_id=? AND event_type='pageview' AND is_bot=0 AND occurred_at>=NOW()-INTERVAL 30 DAY GROUP BY device,browser,os ORDER BY views DESC LIMIT 50");$q->execute([$siteId]);echo '<div class="panel"><h2>端末・ブラウザ・OS</h2><div class="table-wrap"><table class="wp-list"><tr><th>端末</th><th>ブラウザ</th><th>OS</th><th>PV</th></tr>';foreach($q as $r)echo '<tr><td>'.e($r['device']).'</td><td>'.e($r['browser']).'</td><td>'.e($r['os']).'</td><td>'.number_format((int)$r['views']).'</td></tr>';echo '</table></div></div>';
    $q=$db->prepare("SELECT page_title,page_url,referrer_host,device,occurred_at FROM raw_events WHERE site_id=? AND event_type='pageview' AND is_bot=0 AND occurred_at>=NOW()-INTERVAL 30 MINUTE ORDER BY id DESC LIMIT 50");$q->execute([$siteId]);echo '<div class="panel"><h2>リアルタイム（直近30分）</h2><div class="table-wrap"><table class="wp-list"><tr><th>時刻</th><th>ページ</th><th>流入元</th><th>端末</th></tr>';foreach($q as $r)echo '<tr><td>'.e($r['occurred_at']).'</td><td>'.e($r['page_title']?:$r['page_url']).'</td><td>'.e($r['referrer_host']?:'直接').'</td><td>'.e($r['device']).'</td></tr>';echo '</table></div></div>';
}

function asyura_widget_page(PDO $db,string $type,string $title): void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    $edit=(int)($_GET['edit']??0);
    if($edit){$q=$db->prepare('SELECT w.*,s.name site_name FROM widgets w JOIN sites s ON s.id=w.site_id WHERE w.id=? AND w.type=? AND w.site_id=?');$q->execute([$edit,$type,$siteId]);$w=$q->fetch();if(!$w){echo '<div class="notice error">選択中のサイトにこの表示パーツはありません。</div>';return;}$widgetConfig=json_decode((string)$w['config_json'],true)?:[];$feedChecks='';if($type==='rss'){$selected=array_map('intval',(array)($widgetConfig['feed_ids']??[]));foreach($db->query('SELECT f.id,f.name,s.name site_name FROM rss_feeds f JOIN sites s ON s.id=f.site_id WHERE f.active=1 ORDER BY s.name,f.name') as $feed)$feedChecks.='<label><input type="checkbox" name="feed_ids[]" value="'.(int)$feed['id'].'"'.(in_array((int)$feed['id'],$selected,true)?' checked':'').'>'.e($feed['site_name'].' / '.$feed['name']).'</label>';}echo '<form method="post"><input type="hidden" name="action" value="save_widget"><input type="hidden" name="id" value="'.(int)$w['id'].'">'.asyura_context_field().csrf_field().'<div class="panel"><h2>'.e($w['site_name'].' / '.$w['name']).'</h2><div class="panel-body"><label>名称<input name="name" value="'.e($w['name']).'"></label><div class="checks"><label><input type="checkbox" name="enabled" '.($w['enabled']?'checked':'').'>表示する</label>'.($type==='rss'?'<label><input type="checkbox" name="image_required" '.(!empty($widgetConfig['image_required'])?'checked':'').'>RSS内に画像がある記事だけ</label>':'').'</div>'.($type==='rss'?'<h3>表示するRSS</h3><p class="description">未選択の場合はすべての有効なRSSを対象にします。</p><div class="checks">'.$feedChecks.'</div>':'').'<div class="form-grid"><label>表示件数<input type="number" min="1" max="100" name="item_limit" value="'.(int)$w['item_limit'].'"></label><label>横幅<input name="width" value="'.e($w['width']).'"></label><label>高さ<input name="height" value="'.e($w['height']).'"></label></div><label>HTMLテンプレート<textarea name="template_html">'.e($w['template_html']).'</textarea></label><label>CSS<textarea name="custom_css">'.e($w['custom_css']).'</textarea></label><p class="description">使用可能：{title} {url} {description} {category} {rank} {in_count} {out_count} {site_name} {rss_name} {image} {image_tag} {published_at} {rel} {target}</p><button class="button primary">保存</button></div></div></form><div class="panel"><h2>設置タグ</h2><div class="panel-body"><pre class="codebox" id="widget-tag">'.e('<iframe src="'.app_url('widgets/'.$type.'.php?id='.$w['public_id']).'" loading="lazy" style="width:'.$w['width'].';height:'.$w['height'].';border:0"></iframe>').'</pre><button class="button" data-copy="#widget-tag">コピー</button></div></div>';return;}
    echo '<div class="section-intro"><div><h2>'.e(asyura_current_site()['name']).'の'.$title.'</h2><p>表示場所ごとにHTML・CSS・サイズを設定できます。</p></div></div>';
    $q=$db->prepare('SELECT w.*,s.name site_name FROM widgets w JOIN sites s ON s.id=w.site_id WHERE w.type=? AND w.site_id=? ORDER BY w.slot_code');$q->execute([$type,$siteId]);echo '<div class="table-wrap"><table class="wp-list"><tr><th>表示場所</th><th>名称</th><th>状態</th><th>件数</th></tr>';foreach($q as $w)echo '<tr><td><span class="slot-badge">'.e($w['slot_code']).'</span></td><td><a href="'.e(app_url('admin/?page='.$type.'&site='.$siteId.'&edit='.$w['id'])).'">'.e($w['name']).'</a></td><td>'.($w['enabled']?'<span class="badge active">表示</span>':'<span class="badge">停止</span>').'</td><td>'.(int)$w['item_limit'].'</td></tr>';echo '</table></div>';
}
function asyura_page_ranking(PDO $db,array $config):void{asyura_widget_page($db,'ranking','逆アクセスランキング');}

function asyura_page_links(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    if(isset($_GET['widgets'])){asyura_widget_page($db,'links','相互リンク');return;} $edit=(int)($_GET['edit']??0);$link=['id'=>0,'site_id'=>$siteId,'partner_name'=>'','partner_url'=>'','description'=>'','category'=>'','slots'=>'A','status'=>'pending','rel_type'=>'follow','open_new_tab'=>1,'is_priority'=>0,'is_special'=>0,'is_rescue'=>0,'is_excluded'=>0];if($edit){$q=$db->prepare('SELECT * FROM reciprocal_links WHERE id=? AND site_id=?');$q->execute([$edit,$siteId]);$link=$q->fetch()?:$link;}
    echo '<div class="page-actions"><a class="button" href="'.e(app_url('admin/?page=links&site='.$siteId.'&widgets=1')).'">A〜Eの表示デザイン</a></div><div class="panel"><h2>'.($edit?'相互リンクを編集':'提携サイトを追加').'</h2><div class="panel-body"><p class="description">ここには「'.e(asyura_current_site()['name']).'」に掲載する相互リンク先を登録します。</p><form method="post"><input type="hidden" name="action" value="save_link"><input type="hidden" name="id" value="'.(int)$link['id'].'"><input type="hidden" name="site_id" value="'.$siteId.'">'.asyura_context_field().csrf_field().'<div class="form-grid"><label>提携サイト名<input name="partner_name" value="'.e($link['partner_name']).'" required></label><label>提携サイトURL<input type="url" name="partner_url" value="'.e($link['partner_url']).'" required></label><label>カテゴリー<input name="category" value="'.e($link['category']).'"></label><label>状態<select name="status">';foreach(['pending'=>'確認中','approved'=>'承認','paused'=>'停止','rejected'=>'見送り','removed'=>'解除'] as $k=>$v)echo '<option value="'.$k.'"'.($link['status']===$k?' selected':'').'>'.$v.'</option>';echo '</select></label><label>リンク属性<select name="rel_type">';foreach(['follow'=>'通常','nofollow'=>'nofollow','sponsored'=>'sponsored','ugc'=>'ugc'] as $k=>$v)echo '<option value="'.$k.'"'.($link['rel_type']===$k?' selected':'').'>'.$v.'</option>';echo '</select></label></div><label>説明<textarea name="description">'.e($link['description']).'</textarea></label><div class="checks">';foreach(range('A','E') as $slot)echo '<label><input type="checkbox" name="slots[]" value="'.$slot.'"'.(in_array($slot,explode(',',$link['slots']),true)?' checked':'').'>'.$slot.'に表示</label>';echo '</div><div class="checks"><label><input type="checkbox" name="open_new_tab" '.($link['open_new_tab']?'checked':'').'>新しいタブ</label><label><input type="checkbox" name="is_priority" '.($link['is_priority']?'checked':'').'>優遇</label><label><input type="checkbox" name="is_special" '.($link['is_special']?'checked':'').'>特別</label><label><input type="checkbox" name="is_rescue" '.($link['is_rescue']?'checked':'').'>弱小救済</label><label><input type="checkbox" name="is_excluded" '.($link['is_excluded']?'checked':'').'>除外</label></div><button class="button primary">保存</button></form></div></div>';
    $rowStmt=$db->prepare('SELECT l.*,s.name site_name FROM reciprocal_links l JOIN sites s ON s.id=l.site_id WHERE l.site_id=? ORDER BY l.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="section-intro"><div><h2>提携サイト一覧</h2><p>'.e(asyura_current_site()['name']).'に登録された相互リンク先です。</p></div><span class="count-badge">'.count($rows).'件</span></div><div class="table-wrap"><table class="wp-list"><tr><th>提携サイト</th><th>表示場所</th><th>状態</th><th></th></tr>';foreach($rows as $r)echo '<tr><td><a href="'.e($r['partner_url']).'" target="_blank" rel="noopener">'.e($r['partner_name']).'</a></td><td>'.e($r['slots']).'</td><td>'.e($r['status']).'</td><td><a href="'.e(app_url('admin/?page=links&site='.$siteId.'&edit='.$r['id'])).'">編集</a></td></tr>';if(!$rows)echo '<tr><td colspan="4" class="empty">提携サイトはまだありません。</td></tr>';echo '</table></div>';
}

function asyura_page_requests(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    $edit=(int)($_GET['edit']??0);if($edit){$q=$db->prepare('SELECT r.*,s.name target_name FROM link_requests r JOIN sites s ON s.id=r.site_id WHERE r.id=? AND r.site_id=?');$q->execute([$edit,$siteId]);$r=$q->fetch();if(!$r){echo '<div class="empty">選択中のサイトにこの依頼はありません。</div>';return;}echo '<div class="panel"><h2>'.e($r['site_name']).'</h2><div class="panel-body"><p>対象：'.e($r['target_name']).'</p><p>URL：<a href="'.e($r['site_url']).'" target="_blank" rel="noopener">'.e($r['site_url']).'</a></p><p>メール：'.e($r['email']).'</p><p>メッセージ：'.nl2br(e($r['message'])).'</p><form method="post"><input type="hidden" name="action" value="update_request"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<label>状態<select name="status">';foreach(['new'=>'未確認','reviewing'=>'確認中','approved'=>'承認','rejected'=>'見送り','registered'=>'登録完了','removed'=>'解除完了'] as $k=>$v)echo '<option value="'.$k.'"'.($r['status']===$k?' selected':'').'>'.$v.'</option>';echo '</select></label><label>申請者へのメッセージ<textarea name="public_message">'.e($r['public_message']).'</textarea></label><label>解除理由<textarea name="removal_reason">'.e($r['removal_reason']).'</textarea></label><div class="checks"><label><input type="checkbox" name="notify_status_page" '.($r['notify_status_page']?'checked':'').'>確認ページで知らせる</label><label><input type="checkbox" name="notify_email" '.($r['notify_email']?'checked':'').'>メールで知らせる</label><label><input type="checkbox" name="publish_notice" '.($r['publish_notice']?'checked':'').'>公開お知らせへ掲載</label></div><button class="button primary">更新</button></form></div></div>';return;}
    $rowStmt=$db->prepare('SELECT r.*,s.name target_name FROM link_requests r JOIN sites s ON s.id=r.site_id WHERE r.site_id=? ORDER BY r.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="section-intro"><div><h2>'.e(asyura_current_site()['name']).'への相互リンク依頼</h2><p>ほかの管理サイトの依頼は表示されません。</p></div><span class="count-badge">'.count($rows).'件</span></div><div class="table-wrap"><table class="wp-list"><tr><th>受付番号</th><th>申請サイト</th><th>状態</th><th>受付日時</th></tr>';foreach($rows as $r)echo '<tr><td><a href="'.e(app_url('admin/?page=requests&site='.$siteId.'&edit='.$r['id'])).'">'.e($r['receipt_no']).'</a></td><td>'.e($r['site_name']).'</td><td>'.e($r['status']).'</td><td>'.e($r['created_at']).'</td></tr>';if(!$rows)echo '<tr><td colspan="4" class="empty">相互リンク依頼はありません。</td></tr>';echo '</table></div>';
}

function asyura_page_rss(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    if(isset($_GET['widgets'])){asyura_widget_page($db,'rss','相互RSS');return;}echo '<div class="page-actions"><a class="button" href="'.e(app_url('admin/?page=rss&site='.$siteId.'&widgets=1')).'">A〜Jの表示デザイン</a></div><div class="panel"><h2>'.e(asyura_current_site()['name']).'のRSSを追加</h2><div class="panel-body"><p class="description">アンテナサイトの場合も、このサイトに複数のRSSを登録できます。</p><form method="post"><input type="hidden" name="action" value="save_feed"><input type="hidden" name="site_id" value="'.$siteId.'">'.asyura_context_field().csrf_field().'<div class="form-grid"><label>RSS名<input name="name" required></label><label>RSS URL<input type="url" name="feed_url" required></label></div><div class="checks"><label><input type="checkbox" name="active" checked>取得する</label></div><button class="button primary">追加</button></form></div></div>';
    $rowStmt=$db->prepare('SELECT f.*,s.name site_name FROM rss_feeds f JOIN sites s ON s.id=f.site_id WHERE f.site_id=? ORDER BY f.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="section-intro"><div><h2>登録RSS一覧</h2><p>現在選択中のサイトに登録されたRSSだけを表示しています。</p></div><span class="count-badge">'.count($rows).'件</span></div><div class="table-wrap"><table class="wp-list"><tr><th>RSS</th><th>最終成功</th><th>状態</th><th></th></tr>';foreach($rows as $r)echo '<tr><td><strong>'.e($r['name']).'</strong><br><small>'.e($r['feed_url']).'</small></td><td>'.e($r['last_success_at']?:'未取得').'</td><td>'.($r['last_error']?'<span class="badge special">エラー</span><br><small>'.e($r['last_error']).'</small>':'<span class="badge active">正常</span>').'</td><td><form method="post" data-confirm="このRSSを削除しますか？"><input type="hidden" name="action" value="delete_feed"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<button class="button danger">削除</button></form></td></tr>';if(!$rows)echo '<tr><td colspan="4" class="empty">RSSはまだ登録されていません。</td></tr>';echo '</table></div>';
}

function asyura_page_rotation(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    $feedStmt=$db->prepare('SELECT id,name FROM rss_feeds WHERE site_id=? AND active=1 ORDER BY name');$feedStmt->execute([$siteId]);$feedChecks='';foreach($feedStmt as $feed)$feedChecks.='<label><input type="checkbox" name="feed_ids[]" value="'.(int)$feed['id'].'">'.e($feed['name']).'</label>';echo '<div class="panel"><h2>'.e(asyura_current_site()['name']).'の過去記事再配信RSSを追加</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="save_rotation"><input type="hidden" name="site_id" value="'.$siteId.'">'.asyura_context_field().csrf_field().'<div class="form-grid"><label>スラッグ<input name="slug" value="random-post" required></label><label>カテゴリー（空欄は全記事）<input name="category"></label><label>切替間隔<select name="interval_minutes">';foreach([10=>'10分',20=>'20分',30=>'30分',60=>'60分',180=>'3時間',360=>'6時間',720=>'12時間',1440=>'24時間'] as $k=>$v)echo '<option value="'.$k.'">'.$v.'</option>';echo '</select></label></div><h3>対象RSS</h3><p class="description">未選択の場合は、このサイトに登録された全RSSの記事が対象です。</p><div class="checks">'.$feedChecks.'</div><div class="checks"><label><input type="checkbox" name="image_required">画像のある記事だけ</label><label><input type="checkbox" name="active" checked>配信する</label></div><button class="button primary">追加</button></form></div></div><div class="panel"><h2>過去記事をCSVから取り込む</h2><div class="panel-body"><form method="post" action="'.e(app_url('admin/import_articles.php')).'" enctype="multipart/form-data"><input type="hidden" name="site_id" value="'.$siteId.'">'.csrf_field().'<p class="description">取込先：<strong>'.e(asyura_current_site()['name']).'</strong></p><label>CSVファイル<input type="file" name="csv_file" accept=".csv,text/csv" required></label><p class="description">1行目：title,url,description,category,image_url,published_at（titleとurlは必須）／最大5MB・20,000件</p><button class="button primary">取り込む</button></form></div></div>';
    $rowStmt=$db->prepare('SELECT r.*,s.name site_name,s.public_id FROM rotation_feeds r JOIN sites s ON s.id=r.site_id WHERE r.site_id=? ORDER BY r.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="table-wrap"><table class="wp-list"><tr><th>RSS URL</th><th>条件</th><th>状態</th><th></th></tr>';foreach($rows as $r){$url=app_url('feed/random.php?site='.$r['public_id'].'&slug='.$r['slug'].($r['category']?'&category='.rawurlencode($r['category']):''));echo '<tr><td><a href="'.e($url).'" target="_blank">'.e($url).'</a></td><td>'.(int)$r['interval_minutes'].'分 / '.e($r['category']?:'全記事').'</td><td>'.($r['active']?'<span class="badge active">配信</span>':'停止').'</td><td><form method="post" data-confirm="削除しますか？"><input type="hidden" name="action" value="delete_rotation"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<button class="button danger">削除</button></form></td></tr>';}if(!$rows)echo '<tr><td colspan="4" class="empty">再配信RSSはまだありません。</td></tr>';echo '</table></div>';
}

function asyura_page_notices(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    echo '<div class="panel"><h2>'.e(asyura_current_site()['name']).'のお知らせを追加</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="save_notice"><input type="hidden" name="site_id" value="'.$siteId.'">'.asyura_context_field().csrf_field().'<label>タイトル<input name="title" required></label><label>本文<textarea name="body" required></textarea></label><div class="form-grid"><label>種類<select name="notice_type"><option value="normal">通常</option><option value="important">重要</option><option value="maintenance">メンテナンス</option><option value="registered">登録完了</option><option value="removed">解除完了</option></select></label><label>公開開始<input type="datetime-local" name="starts_at"></label><label>公開終了<input type="datetime-local" name="ends_at"></label></div><div class="checks"><label><input type="checkbox" name="all_sites">全管理サイト共通のお知らせにする</label><label><input type="checkbox" name="is_public" checked>外部サイトへ公開</label><label><input type="checkbox" name="is_pinned">上部固定</label></div><button class="button primary">追加</button></form></div></div>';
    $rowStmt=$db->prepare('SELECT n.*,s.name site_name FROM notices n LEFT JOIN sites s ON s.id=n.site_id WHERE n.site_id=? OR n.site_id IS NULL ORDER BY n.is_pinned DESC,n.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="table-wrap"><table class="wp-list"><tr><th>タイトル</th><th>対象</th><th>種類</th><th>公開</th><th></th></tr>';foreach($rows as $r)echo '<tr><td><strong>'.e($r['title']).'</strong><br><small>'.e(mb_substr($r['body'],0,80)).'</small></td><td>'.e($r['site_name']?:'全サイト共通').'</td><td>'.e($r['notice_type']).'</td><td>'.($r['is_public']?'公開':'管理画面のみ').'</td><td><form method="post" data-confirm="削除しますか？"><input type="hidden" name="action" value="delete_notice"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<button class="button danger">削除</button></form></td></tr>';echo '</table></div><div class="panel"><h2>お知らせ表示タグ</h2><div class="table-wrap"><table class="wp-list"><tr><th>表示場所</th><th>タグ</th></tr>';$widgetStmt=$db->prepare("SELECT * FROM widgets WHERE type='notices' AND site_id=? ORDER BY slot_code");$widgetStmt->execute([$siteId]);foreach($widgetStmt as $w){$tag='<iframe src="'.app_url('widgets/notices.php?id='.$w['public_id']).'" loading="lazy" style="width:'.$w['width'].';height:'.$w['height'].';border:0"></iframe>';echo '<tr><td>'.e($w['slot_code']).'</td><td><code>'.e($tag).'</code></td></tr>';}echo '</table></div></div>';
}

function asyura_page_urls(PDO $db,array $config):void
{
    $siteId=asyura_require_current_site();if(!$siteId)return;
    echo '<div class="panel"><h2>'.e(asyura_current_site()['name']).'の別URLを追加</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="save_alias"><input type="hidden" name="site_id" value="'.$siteId.'">'.asyura_context_field().csrf_field().'<div class="form-grid"><label>別URL・旧URL<input type="url" name="alias_url" required></label><label>判定方法<select name="match_type"><option value="host">ドメイン一致</option><option value="prefix">先頭一致</option><option value="contains">含む</option><option value="exact">完全一致</option></select></label></div><div class="checks"><label><input type="checkbox" name="allow_tracking_origin">このURLにも計測タグを設置する（旧ドメイン・サブドメイン用）</label></div><p class="description">iframeや外部ランキングツールのURLではチェックしないでください。</p><button class="button primary">追加</button></form></div></div>';
    $rowStmt=$db->prepare('SELECT a.*,s.name site_name FROM site_aliases a JOIN sites s ON s.id=a.site_id WHERE a.site_id=? ORDER BY a.id DESC');$rowStmt->execute([$siteId]);$rows=$rowStmt->fetchAll();echo '<div class="table-wrap"><table class="wp-list"><tr><th>登録URL</th><th>正規化後</th><th>判定</th><th>タグ</th><th></th></tr>';foreach($rows as $r)echo '<tr><td>'.e($r['alias_url']).'</td><td>'.e($r['normalized_url']).'</td><td>'.e($r['match_type']).'</td><td>'.($r['allow_tracking_origin']?'設置可':'流入判定のみ').'</td><td><form method="post" data-confirm="削除しますか？"><input type="hidden" name="action" value="delete_alias"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<button class="button danger">削除</button></form></td></tr>';if(!$rows)echo '<tr><td colspan="5" class="empty">別URLは登録されていません。</td></tr>';echo '</table></div><div class="panel global-panel"><h2>全サイト共通：検索エンジン・不要サイトの除外</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="save_excluded_referrer">'.asyura_context_field().csrf_field().'<div class="form-grid"><label>名前<input name="label" required></label><label>パターン<input name="pattern" placeholder="example.com" required></label><label>判定<select name="match_type"><option value="host">ドメイン一致</option><option value="contains">含む</option><option value="exact">完全一致</option></select></label></div><button class="button primary">追加</button></form></div><div class="table-wrap"><table class="wp-list"><tr><th>名前</th><th>パターン</th><th>判定</th><th></th></tr>';foreach($db->query('SELECT * FROM excluded_referrers ORDER BY id') as $r)echo '<tr><td>'.e($r['label']).'</td><td>'.e($r['pattern']).'</td><td>'.e($r['match_type']).'</td><td><form method="post" data-confirm="削除しますか？"><input type="hidden" name="action" value="delete_excluded_referrer"><input type="hidden" name="id" value="'.(int)$r['id'].'">'.asyura_context_field().csrf_field().'<button class="button danger">削除</button></form></td></tr>';echo '</table></div></div><div class="notice info">除外設定は全管理サイトで共通です。除外した流入元は解析には残りますが、ランキングとRSS配分には使用しません。</div>';
}

function asyura_page_data(PDO $db,array $config):void
{
    $exports=$db->query('SELECT * FROM exports ORDER BY export_year DESC,created_at DESC')->fetchAll();echo '<div class="panel"><h2>年次エクスポート</h2><div class="panel-body"><p>1月1日 00:00から12月31日 23:59までをCSV/ZIPで保存します。</p><form method="post" action="'.e(app_url('admin/export.php')).'">'.csrf_field().'<label>対象年<input type="number" name="year" min="2000" max="'.date('Y').'" value="'.(date('Y')-1).'"></label><button class="button primary">エクスポートを作成</button></form></div></div><div class="panel"><h2>エクスポート履歴・アーカイブ閲覧</h2><div class="table-wrap"><table class="wp-list"><tr><th>年</th><th>ファイル</th><th>作成日</th><th></th></tr>';foreach($exports as $r)echo '<tr><td>'.(int)$r['export_year'].'</td><td>'.e($r['file_name']).'</td><td>'.e($r['created_at']).'</td><td><a href="'.e(app_url('admin/archive.php?id='.$r['id'])).'">閲覧・ダウンロード</a></td></tr>';if(!$exports)echo '<tr><td colspan="4" class="empty">エクスポートはまだありません。</td></tr>';echo '</table></div></div><div class="danger-zone"><h2>エクスポート済み年のDBデータを削除</h2><p>アーカイブファイルは残し、指定年のアクセス・配分履歴をDBから削除します。</p><form method="post" action="'.e(app_url('admin/delete_year.php')).'" data-confirm="指定年のデータを削除しますか？"><label>対象年<input type="number" name="year" min="2000" max="'.date('Y').'" value="'.(date('Y')-1).'" required></label><div class="checks"><label><input type="radio" name="confirm_delete" value="no" checked>いいえ</label><label><input type="radio" name="confirm_delete" value="yes">はい、削除します</label></div>'.csrf_field().'<button class="button danger">DBデータを削除</button></form></div>';
}

function asyura_page_settings(PDO $db,array $config):void
{
    echo '<div class="panel"><h2>保存期間・集計</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="save_settings">'.csrf_field().'<div class="form-grid"><label>ランキング対象期間（日）<input type="number" name="ranking_period_days" value="'.e(setting('ranking_period_days',3)).'"></label><label>相互RSS配分期間（時間）<input type="number" name="distribution_window_hours" value="'.e(setting('distribution_window_hours',24)).'"></label><label>生ログ保存（日）<input type="number" name="raw_retention_days" value="'.e(setting('raw_retention_days',180)).'"></label><label>配分履歴保存（日）<input type="number" name="distribution_retention_days" value="'.e(setting('distribution_retention_days',180)).'"></label><label>集計保存（日）<input type="number" name="aggregate_retention_days" value="'.e(setting('aggregate_retention_days',1095)).'"></label><label>通常RSS記事保存（日）<input type="number" name="rss_item_retention_days" value="'.e(setting('rss_item_retention_days',3)).'"></label></div><button class="button primary">保存</button></form></div></div><div class="panel"><h2>ログイン情報変更</h2><div class="panel-body"><form method="post"><input type="hidden" name="action" value="change_password">'.csrf_field().'<label>ユーザー名<input name="new_username" value="'.e($_SESSION['admin_username']??'admin').'" required></label><label>現在のパスワード<input type="password" name="current_password" required></label><label>新しいパスワード（変更しない場合は空欄）<input type="password" name="new_password" minlength="10"></label><button class="button primary">変更</button></form></div></div><div class="panel"><h2>cron</h2><div class="panel-body"><pre class="codebox">'.e(app_url('cron/run.php?key='.$config['cron_key'])).'</pre><p>サーバーのcronを30分ごとに設定してください。</p></div></div>';
}
