<?php
declare(strict_types=1);

use Asyura\SearchConsoleService;

$service=new SearchConsoleService($db,$config);$service->ensureSchema();$status=$service->status();$callback=app_url('admin/search-console-callback.php');$properties=[];$propertyError='';
if($status['connected']){try{$properties=$service->listProperties();}catch(Throwable $e){$propertyError=$e->getMessage();}}
echo '<div class="panel search-console-panel"><h2>Googleアカウント接続（阿修羅全体で1回）</h2><div class="panel-body"><p>同じGoogleアカウントを阿修羅に1回接続し、下の一覧でサイトごとにプロパティを割り当てます。権限は読み取り専用です。</p>';
echo '<div class="notice info"><strong>Google Cloud側の準備</strong><ol><li>Google Cloudで使用するプロジェクトを選択または作成します。</li><li>Search Console APIを有効にします。</li><li>Google Auth Platformの「クライアント」でOAuthクライアントIDを作成し、種類は「ウェブ アプリケーション」を選択します。</li><li>下に表示されている「承認済みリダイレクトURI」をGoogle Cloud側へそのまま登録します。</li><li>発行されたクライアントIDとクライアントシークレットを阿修羅へ保存し、その後「Googleアカウントで接続」を実行します。</li></ol><p><strong>Google Cloud：</strong> <a href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">https://console.cloud.google.com/auth/clients</a></p><div class="actions"><a class="button" href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">Google Cloudを開く ↗</a></div></div>';
echo '<form method="post" class="search-console-form">'.csrf_field().'<input type="hidden" name="action" value="save_search_console_credentials"><div class="form-grid"><label>Google OAuth クライアントID<input name="client_id" value="'.e($status['client_id']).'" autocomplete="off" required></label><label>Google OAuth クライアントシークレット<input type="password" name="client_secret" autocomplete="new-password" placeholder="'.($status['client_secret_readable']?'保存済み（変更時のみ入力）':($status['has_client_secret']?'保存あり（復号できません）':'入力してください')).'"></label><label class="span-2">承認済みリダイレクトURI<input value="'.e($callback).'" readonly></label></div>'.($status['reconnect_required']?'<div class="notice warning"><strong>Google認証の再設定が必要です。</strong><br>'.e($status['recovery_message']).'サイト別プロパティの割り当ては消えません。</div>':'').'<p>シークレットは安全のため表示しません。「保存済み」の場合、空欄のまま保存しても保持されます。同じID・シークレットの再保存では接続は解除されません。</p><div class="actions"><button class="button primary">OAuth設定を保存</button></div></form></div></div>';
echo '<div class="panel search-console-panel"><h2>接続状態</h2><div class="panel-body">';
if($status['connected']){echo '<p><span class="status-pill '.($propertyError===''?'success':'muted').'">'.($propertyError===''?'接続済み':'認証情報保存済み・接続確認失敗').'</span> '.e((string)($status['connected_at']??'')).'</p><div class="actions"><a class="button" href="'.e(app_url('admin/search-console-connect.php')).'">Googleアカウントを再接続</a><form method="post">'.csrf_field().'<input type="hidden" name="action" value="disconnect_search_console"><button class="button danger">接続解除</button></form></div>';}elseif($status['reconnect_required']){echo '<p><span class="security-badge critical">再設定が必要</span> 保存済みのGoogle認証情報を安全に読み込めないため、現在は未接続です。</p><form method="post">'.csrf_field().'<input type="hidden" name="action" value="disconnect_search_console"><button class="button danger">古い接続情報を解除</button></form>';}else{echo '<p>未接続です。</p>';if($status['client_id']!==''&&$status['client_secret_readable'])echo '<a class="button primary" href="'.e(app_url('admin/search-console-connect.php')).'">Googleアカウントで接続</a>';}
if($status['reconnect_required']&&$status['client_secret_readable'])echo '<a class="button primary" href="'.e(app_url('admin/search-console-connect.php')).'">Googleアカウントを再接続</a>';
echo '<p>約7日で接続が切れる場合：Google CloudのOAuth同意画面で、公開ステータスが「テスト」になっていないか確認してください。Search Consoleの権限ではテスト中の更新トークンは7日で失効します。</p>';
echo '</div></div>';
echo '<div class="panel search-console-panel"><h2>サイト別プロパティ設定</h2><div class="panel-body"><p>アンテナサイトなどSearch Consoleへ登録しないサイトは「使用しない」のままで構いません。</p>';
if($propertyError!=='')echo '<div class="notice error">'.e($propertyError).'</div>';
echo '<form method="post">'.csrf_field().'<input type="hidden" name="action" value="save_search_console_properties"><div class="table-wrap"><table class="wp-list search-console-table"><thead><tr><th>サイト</th><th>Search Consoleプロパティ</th><th>状態</th></tr></thead><tbody>';
foreach($asyuraSites as $site){$current=(string)($site['search_console_property']??'');echo '<tr><td data-label="サイト"><strong>'.e($site['name']).'</strong><br><small>'.e($site['url']).'</small></td><td data-label="プロパティ"><select name="properties['.(int)$site['id'].']"><option value="">使用しない（アンテナサイト等）</option>';$seen=false;foreach($properties as $property){$value=(string)$property['siteUrl'];if($value===$current)$seen=true;echo '<option value="'.e($value).'"'.($value===$current?' selected':'').'>'.e($value).'</option>';}if($current!==''&&!$seen)echo '<option value="'.e($current).'" selected>'.e($current).'（現在設定・一覧外）</option>';echo '</select></td><td data-label="状態">'.($current!==''?'<span class="status-pill success">設定済み</span>':'<span class="status-pill muted">未使用</span>').'</td></tr>';}
if($asyuraSites===[])echo '<tr><td colspan="3" class="empty">登録サイトがありません。</td></tr>';
echo '</tbody></table></div><div class="actions"><button class="button primary">サイト別設定を保存</button></div></form></div></div>';
